---
# Source: influxdb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: alameda-influxdb
  labels:
    app: alameda-influxdb
    chart: "influxdb-1.3.3"
    release: "alameda-influxdb"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 8086
    targetPort: 8086
  - name: rpc
    port: 8088
    targetPort: 8088
  selector:
    app: alameda-influxdb
