---
# Source: alameda/templates/crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: alamedascalers.autoscaling.containers.ai
spec:
  group: autoscaling.containers.ai
  names:
    kind: AlamedaScaler
    plural: alamedascalers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description:
            "APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources"
          type: string
        kind:
          description:
            "Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"
          type: string
        metadata:
          type: object
        spec:
          properties:
            customResourceVersion:
              type: string
            enableExecution:
              type: boolean
            policy:
              enum:
              - stable
              - compact
              type: string
            scalingTools:
              items:
                enum:
                - vpa
                - hpa
                type: string
              type: array
            selector:
              description:
                'Important: Run "make" to regenerate code after modifying
                this file'
              type: object
          required:
            - selector
          type: object
        status:
          properties:
            alamedaController:
              properties:
                deploymentConfigs:
                  type: object
                deployments:
                  type: object
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: alamedarecommendations.autoscaling.containers.ai
spec:
  group: autoscaling.containers.ai
  names:
    kind: AlamedaRecommendation
    plural: alamedarecommendations
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            containers:
              items:
                properties:
                  name:
                    type: string
                  resources:
                    type: object
                required:
                  - name
                type: object
              type: array
          required:
            - containers
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
